### ISSUE TITLE
Create Cards

### ISSUE THREAD

**Issue by mgerweck** [COSC-481W-Dodo/dodo-web#15]
**PBI, Create Cards (Web): As a student user of Dodo, I would like to create cards and have them saved to my account.**

- [x] Add a “Create” button to the navbar.
- [x] Add a “Create Cards” page.
- [x] Add an “Insert Tags” section at the top of the “Create Cards” page.
- [x] Include an “Add Card” button below the latest card.
- [x] Include a “Save Cards” button at the bottom of the page to save cards to the database.

**Acceptance Criteria**

- Once logged in, a button should exist either in the navigation bar or on the welcome screen which directs the user to a screen where they can create a set of cards that all share the same tags.
- On this screen, the user should be able to add tags - and they must have at least one. Prevent user from saving if there are no tags added.
- On this screen, the user should be able to add flashcards - and they must have at least one. Prevent user from saving if there are no cards.
- There should be a button to save the cards.

**Comment by sjiang1** [comment]
Add the following criteria:

- Once the user clicks the save button, the cards will be saved with the tags.
