### ISSUE TITLE
Polish UI/UX

### ISSUE THREAD

**Issue by mgerweck** [COSC-481W-Dodo/dodo-web#16]
**PBI, Polish UI/UX: As a student user of Dodo, I would like to have a nice app to look at and a frustration-free experience using the app.**

- [x] Conditional renders on navbar (login/registration links).
- [x] Redirect after successful login.
- [x] Simplify form validation on the login screen.
- [x] Reduce required inputs on the login page to email and password.
- [x] Restrict access to login and registration after the user is already logged in.
- [x] Logout button

**Acceptance Criteria**

- Login & Registration links on the navbar should disappear after successfully logging in.
- There should not be view or edit accounts when the user is not logged in.
- Implement a logout feature
- Login & Registration pages should be inaccessible if the user is logged in.
- Fix form validation for the login page. It only needs to check if the information is correct (no checks on password criteria and valid email), and it only needs email and password fields.

**Comment by jgenove1** [comment]
Closed by above PR
